api/urls.py
from django.contrib import admin # type: ignore
from django.urls import path, include # type: ignore

from django.conf.urls.static import static #static is a function that we need # type: ignore
from django.conf import settings # type: ignore

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("home.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

example/urls.py
# example/urls.py
from django.urls import path

from example.views import index


urlpatterns = [
    path('', index),
]

home/urls.py
from django.urls import path # type: ignore
from . import views

app_name = "home"

urlpatterns = [
    path("", views.index, name = "index"),
]

home/models.py
from django.db import models

# Create your models here.

home/views.py
from django.shortcuts import render # type: ignore

# Create your views here.
def index(request):
    context = {}
    return render(request, "home/index.html", context)

templates/base.html
<!DOCTYPE html>
<html lang="pt-br">
    <head>
        {% load static %}
        <link rel="icon" type="image/png" href="{% static 'images/favicon.png' %}">
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>{% block title %}{% endblock %}</title>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
        {% block additional_style %}{% endblock %}
      </head>
    <body>
        <header>
            {% if user_is_moderador %}
              {% if request.user.autoescola == autoescola %}
              <nav class="navbar navbar-expand-lg bg-body-tertiary center">
                <div class="container-fluid">
                  <a class="navbar-brand" href="{% url 'home:index' %}">
                    <img class="logo" src="{% static 'images/logo.webp' %}" />
                  </a>
                  <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                  </button>
                  <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                      <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="#add-aluno">Adicionar novo aluno</a>
                      </li>
                    </ul>
                    <div class="button-header">
                          <button id="toggleButton" type="button" class="btn btn-sm btn-second">Visualizar site {{autoescola.nome}}</button>
                          <a href="#"><button type="button" class="btn btn-sm btn-second">Desconectar</button></a>
                    </div>
                  </div>
                </div>
              </nav>
              {% endif %}
            {% elif autoescola %}
              <nav class="navbar navbar-expand-lg bg-body-tertiary center">
                <div class="container-fluid">
                  <a class="navbar-brand" href="#">
                    <img class="logo" src="{{ autoescola.logo.url }}"/>
                  </a>
                  <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                  </button>
                  <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                      <li class="nav-item"><a class="nav-link active" aria-current="page" href="{% url 'inicial:index' %}#sobre-nos">Whatsapp</a></li>
                      <li class="nav-item dropdown"><a class="nav-link" href="#">Localizaçao</a></li>
                      <li class="nav-item dropdown"><a class="nav-link" href="#">Beneficios</a></li>
                    </ul>
                  </div>
                </div>
              </nav>
        
            {% else %}
              <nav class="navbar navbar-expand-lg bg-body-tertiary center">
                <div class="container-fluid">
                  <a class="navbar-brand" href="#">
                    <img class="logo" src="{% static 'images/logo.webp' %}" />
                  </a>
                  <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                  </button>
                  <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                     
                      <li class="nav-item">
                        <a class="nav-link" href="#">Criar site autoescola</a>
                      </li>
                      <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Politicas</a>
                        <ul class="dropdown-menu">
                          <li><a class="dropdown-item" href="#">Politica de Privacidade</a></li>
                          <li><a class="dropdown-item" href="#">Termos de Uso</a></li>
                          <li><a class="dropdown-item" href="#">Política de Cookies</a></li>
                        </ul>
                      </li>
                    </ul>
                    <div class="button-header">
                        {% if not user.is_authenticated %}
                          <a href="#"><button type="button" class="btn btn-sm btn-second">Acessar plataforma</button></a>
                        {% else %}
                          <a href="#"><button type="button" class="btn btn-sm btn-second">Sair</button></a>
                        {% endif %}
                    </div>
                  </div>
                </div>
              </nav>
              {% endif %}
            </header>
        <main>
            {% block content %}{% endblock %}
        </main>
        {% if autoescola %}
        <footer>
          <div class="container-sm footer-background">
            <footer class="py-3 my-4">
              <ul class="nav justify-content-center border-bottom pb-3 mb-3 footer-padding">
                <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">{{ autoescola.nome }}</a></li>
                <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">CNPJ: {{ autoescola.cnpj }}</a></li>
                <li class="nav-item"><a href="https://wa.me//55{{autoescola.whatsapp}}" class="nav-link px-2 text-body-secondary">WhatApp</a></li>
              </ul>
              <img class="logo" src="{{ autoescola.logo.url }}" />
            </footer>
          </div>
        </footer>
        {% else %}
        <footer>
          <div class="container footer-background">
            <footer class="py-3 my-4">
              <ul class="nav justify-content-center border-bottom pb-3 mb-3">
                <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">Acelere.org</a></li>
                <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">CNPJ: 42.674.865/0001-83</a></li>
                <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">WhatApp</a></li>
                <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">Políticas</a></li>
              </ul>
              <img class="logo" src="{% static 'images/logo.webp' %}" />
            </footer>
          </div>
        </footer>
        {% endif %}
    </body>
</html>

templates/home/index.html
{% extends "base.html" %}
{% load static %}

{% block title %}Oaizs - Migration Management{% endblock %}

{% block content %}
<div class="container text-center first-sec-inicial-index">
    <div class="row">
      <div class="col">
        <h1 class="h1-home">+1,500 questões do DETRAN para praticar</h1>
        <p class="p-first additional-padding-bottom">Sistema fácil de usar que permite ao aluno se divertir enquanto aprende.</p>
        <a href="https://wa.me/5548998289645"><button type="button" class="btn btn-sm btn-main big"><i class="bi bi-whatsapp"></i>cadastrar autoescola</button></a>
      </div>
      <div class="col">
        <img class="image-header" src="{% static 'images/feature-simulations.webp' %}">
      </div>
    </div>
</div>

<div class="container text-center gray">
    <div class="row">
      <div class="col">
        <img class="image-header" src="{% static 'images/simulado.png' %}">
      </div>
      <div class="col height-index-inicial-sections">
        <ul class="list-group list-group-flush">
            <h3 class="h3-home">Ficou fácil aprender</h3>
            <li class="list-group-item"><i class="bi bi-camera-reels-fill"></i> +300 vídeos curtos selecionados para você</li>
            <li class="list-group-item"><i class="bi bi-file-earmark-play-fill"></i> +1500 questões comentadas com vídeos</li>
            <li class="list-group-item"><i class="bi bi-car-front-fill"></i> Bônus sobre baliza e prática para você arrasar</li>
          </ul>
          <a href="https://wa.me/5548998289645"><button type="button" class="btn btn-sm btn-whatsapp big"><i class="bi bi-whatsapp"></i>fale conosco</button></a>
      </div>
    </div>
</div>

{% endblock %}